// <auto-generated />
using System;
using APISistemaTickets.Modules.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APISistemaTickets.Migrations.SqlServerMigrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220613024951_TicketSystem")]
    partial class TicketSystem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APISistemaTickets.Modules.Comments.Domain.Entities.Comment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentId"), 1L, 1);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.KnowledgeBase.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.Property<long>("KnowledgeBaseArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KnowledgeBaseArticleId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("KnowledgeBaseArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("KnowledgeBaseArticles");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.Tags.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagId"), 1L, 1);

                    b.Property<long?>("KnowledgeBaseArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.HasIndex("KnowledgeBaseArticleId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.Tickets.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EngineerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.UserAdministration.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TagTicket", b =>
                {
                    b.Property<long>("TagsTagId")
                        .HasColumnType("bigint");

                    b.Property<long>("TicketsId")
                        .HasColumnType("bigint");

                    b.HasKey("TagsTagId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("TagTicket");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.Comments.Domain.Entities.Comment", b =>
                {
                    b.HasOne("APISistemaTickets.Modules.Tickets.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APISistemaTickets.Modules.UserAdministration.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.KnowledgeBase.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.HasOne("APISistemaTickets.Modules.UserAdministration.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.Tags.Domain.Entities.Tag", b =>
                {
                    b.HasOne("APISistemaTickets.Modules.KnowledgeBase.Domain.Entities.KnowledgeBaseArticle", "KnowledgeBaseArticle")
                        .WithMany("Tags")
                        .HasForeignKey("KnowledgeBaseArticleId");

                    b.Navigation("KnowledgeBaseArticle");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.Tickets.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("APISistemaTickets.Modules.UserAdministration.Domain.Entities.User", "Engineer")
                        .WithMany()
                        .HasForeignKey("EngineerId");

                    b.HasOne("APISistemaTickets.Modules.UserAdministration.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engineer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TagTicket", b =>
                {
                    b.HasOne("APISistemaTickets.Modules.Tags.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APISistemaTickets.Modules.Tickets.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APISistemaTickets.Modules.KnowledgeBase.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("APISistemaTickets.Modules.Tickets.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
